FROM ubuntu:16.04
MAINTAINER Rodrigo dos Santos
LABEL version="1.0" description="ubuntu server TOTVS Protheus 12.1.27"
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y unzip
RUN apt-get clean